# R 과 Python 8주차 - 제2강

## Python 유용한 패키지들

다음 셀은, 이후의 셀에서, 각 셀에서 여러 개의 출력를
표시하도록 하는 옵션 설정 변경임

In [2]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity="all"

### numpy / pandas

In [3]:
import numpy as np
import pandas as pd

### numpy

In [4]:
xa = np.arange(1,12+1)
xr = np.random.choice(xa,9)
xa
xr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

array([ 7,  3, 12, 11,  8, 11,  8,  7,  9])

xa 는 1부터 12까지의 수열,

xr 은 xa 로부터 랜덤하게 뽑은 9개의 숫자 (1 차원 array)

xr 의 형태를 바꾸어 (3,3) 행렬로 만들자

In [5]:
xr3 = xr.reshape(3,3)
xr3

array([[ 7,  3, 12],
       [11,  8, 11],
       [ 8,  7,  9]])

In [5]:
xr.shape
xr3.shape

(9,)

(3, 3)

In [6]:
xz= xr3.reshape((3,1,3))
xz

array([[[ 7,  3, 12]],

       [[11,  8, 11]],

       [[ 8,  7,  9]]])

In [7]:
xz.shape

(3, 1, 3)

In [9]:
xz.reshape((-1,3))

array([[ 7,  3, 12],
       [11,  8, 11],
       [ 8,  7,  9]])

In [10]:
xz

array([[[ 7,  3, 12]],

       [[11,  8, 11]],

       [[ 8,  7,  9]]])

In [11]:
xz.squeeze()

array([[ 7,  3, 12],
       [11,  8, 11],
       [ 8,  7,  9]])

In [12]:
xz.squeeze().shape

(3, 3)

3x3 단위행렬을 만들어 보자  
> eye: 단위행렬을 만듦

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

3x3 형태의 0 행렬을 만들어 보자

In [14]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

행렬에 숫자를 더하면, 행렬의 모든 원소에 숫자가 더해진다 ( bradcasting )

In [19]:
np.zeros((3,3))+1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [20]:
np.zeros((3,3)) + 1 + np.eye(3)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

In [21]:
xr

array([ 7,  3, 12, 11,  8, 11,  8,  7,  9])

In [22]:
+xr

array([ 7,  3, 12, 11,  8, 11,  8,  7,  9])

In [23]:
np.zeros((3,3))+1+np.eye(3)
xr.reshape(3,3)

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])

array([[ 7,  3, 12],
       [11,  8, 11],
       [ 8,  7,  9]])

In [24]:
xm = np.zeros((3,3))+1+np.eye(3)+xr.reshape(3,3)
xm

array([[ 9.,  4., 13.],
       [12., 10., 12.],
       [ 9.,  8., 11.]])

In [25]:
xm

array([[ 9.,  4., 13.],
       [12., 10., 12.],
       [ 9.,  8., 11.]])

In [26]:
xm[0:2, 0:2]

array([[ 9.,  4.],
       [12., 10.]])

In [27]:
xm[[0,1], [0,1]]

array([ 9., 10.])

#### pandas

In [28]:
xm

array([[ 9.,  4., 13.],
       [12., 10., 12.],
       [ 9.,  8., 11.]])

In [30]:
xp = pd.DataFrame(xm)
xp

0     1     2
0   9.0   4.0  13.0
1  12.0  10.0  12.0
2   9.0   8.0  11.0

In [33]:
xm.__class__
#numpy.ndarrary

numpy.ndarray

In [34]:
xp.__class__
#pandas.core.frame.DataFrame

pandas.core.frame.DataFrame

In [35]:
xp

0     1     2
0   9.0   4.0  13.0
1  12.0  10.0  12.0
2   9.0   8.0  11.0

In [36]:
xm[0] #xm의 0번째 행
xp[0] #xp의 0번째 열

array([ 9.,  4., 13.])

0     9.0
1    12.0
2     9.0
Name: 0, dtype: float64

In [37]:
xp[[0]]

0
0   9.0
1  12.0
2   9.0

In [40]:
xp[0].shape
#(3,) 3열 벡터

(3,)

In [41]:
xp[[0]].shape
#(3, 1) 3열 1행

(3, 1)

In [42]:
dict(xp)

{0: 0     9.0
 1    12.0
 2     9.0
 Name: 0, dtype: float64,
 1: 0     4.0
 1    10.0
 2     8.0
 Name: 1, dtype: float64,
 2: 0    13.0
 1    12.0
 2    11.0
 Name: 2, dtype: float64}

In [46]:
xp
xp[:2] #2행 선택
xp[:2][[0,2]] #2행, 0열2열 선택

0     1     2
0   9.0   4.0  13.0
1  12.0  10.0  12.0
2   9.0   8.0  11.0

0     1     2
0   9.0   4.0  13.0
1  12.0  10.0  12.0

0     2
0   9.0  13.0
1  12.0  12.0

In [47]:
xp.iloc[[0,2],[0,2]] #0행2행, 0열2열 선택

0     2
0  9.0  13.0
2  9.0  11.0

In [49]:
xa = xp.copy()
xa.columns = list('abc') #변수 이름 변경 
xa

a     b     c
0   9.0   4.0  13.0
1  12.0  10.0  12.0
2   9.0   8.0  11.0

In [50]:
xp
xa

0     1     2
0   9.0   4.0  13.0
1  12.0  10.0  12.0
2   9.0   8.0  11.0

a     b     c
0   9.0   4.0  13.0
1  12.0  10.0  12.0
2   9.0   8.0  11.0

In [52]:
#iloc: 콤마를 놓고 앞뒤로 행과 열 구별
xp.iloc[0:2, 0:2]

0     1
0   9.0   4.0
1  12.0  10.0

In [53]:
xp.loc[0:2, 0:2]

0     1     2
0   9.0   4.0  13.0
1  12.0  10.0  12.0
2   9.0   8.0  11.0

In [54]:
xa.loc[:, :'b']

a     b
0   9.0   4.0
1  12.0  10.0
2   9.0   8.0